[package]
name = "wasmtime-min-repo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "17.0.0"
wasmtime-wasi = "17.0.0"
wasi-common = "17.0.0"
anyhow = "1.0.79"
